// MIT License
//
// Copyright (c) 2021 Michal Baczun and EASE lab
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: proto/videoservice.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DecodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Video []byte `protobuf:"bytes,1,opt,name=video,proto3" json:"video,omitempty"`
	S3Key string `protobuf:"bytes,2,opt,name=s3key,proto3" json:"s3key,omitempty"`
}

func (x *DecodeRequest) Reset() {
	*x = DecodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_videoservice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodeRequest) ProtoMessage() {}

func (x *DecodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_videoservice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodeRequest.ProtoReflect.Descriptor instead.
func (*DecodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_videoservice_proto_rawDescGZIP(), []int{0}
}

func (x *DecodeRequest) GetVideo() []byte {
	if x != nil {
		return x.Video
	}
	return nil
}

func (x *DecodeRequest) GetS3Key() string {
	if x != nil {
		return x.S3Key
	}
	return ""
}

type DecodeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Classification string `protobuf:"bytes,1,opt,name=classification,proto3" json:"classification,omitempty"`
}

func (x *DecodeReply) Reset() {
	*x = DecodeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_videoservice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecodeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodeReply) ProtoMessage() {}

func (x *DecodeReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_videoservice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodeReply.ProtoReflect.Descriptor instead.
func (*DecodeReply) Descriptor() ([]byte, []int) {
	return file_proto_videoservice_proto_rawDescGZIP(), []int{1}
}

func (x *DecodeReply) GetClassification() string {
	if x != nil {
		return x.Classification
	}
	return ""
}

type RecogniseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Frame []byte `protobuf:"bytes,1,opt,name=frame,proto3" json:"frame,omitempty"`
	S3Key string `protobuf:"bytes,2,opt,name=s3key,proto3" json:"s3key,omitempty"`
}

func (x *RecogniseRequest) Reset() {
	*x = RecogniseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_videoservice_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecogniseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecogniseRequest) ProtoMessage() {}

func (x *RecogniseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_videoservice_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecogniseRequest.ProtoReflect.Descriptor instead.
func (*RecogniseRequest) Descriptor() ([]byte, []int) {
	return file_proto_videoservice_proto_rawDescGZIP(), []int{2}
}

func (x *RecogniseRequest) GetFrame() []byte {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *RecogniseRequest) GetS3Key() string {
	if x != nil {
		return x.S3Key
	}
	return ""
}

type RecogniseReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Classification string `protobuf:"bytes,1,opt,name=classification,proto3" json:"classification,omitempty"`
}

func (x *RecogniseReply) Reset() {
	*x = RecogniseReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_videoservice_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecogniseReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecogniseReply) ProtoMessage() {}

func (x *RecogniseReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_videoservice_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecogniseReply.ProtoReflect.Descriptor instead.
func (*RecogniseReply) Descriptor() ([]byte, []int) {
	return file_proto_videoservice_proto_rawDescGZIP(), []int{3}
}

func (x *RecogniseReply) GetClassification() string {
	if x != nil {
		return x.Classification
	}
	return ""
}

var File_proto_videoservice_proto protoreflect.FileDescriptor

var file_proto_videoservice_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x76, 0x69, 0x64, 0x65,
	0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x3b, 0x0a, 0x0d, 0x44, 0x65, 0x63, 0x6f,
	0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x69, 0x64,
	0x65, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x12,
	0x14, 0x0a, 0x05, 0x73, 0x33, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x73, 0x33, 0x6b, 0x65, 0x79, 0x22, 0x35, 0x0a, 0x0b, 0x44, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x26, 0x0a, 0x0e, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6c,
	0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x3e, 0x0a, 0x10,
	0x52, 0x65, 0x63, 0x6f, 0x67, 0x6e, 0x69, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x05, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x33, 0x6b, 0x65, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x33, 0x6b, 0x65, 0x79, 0x22, 0x38, 0x0a, 0x0e,
	0x52, 0x65, 0x63, 0x6f, 0x67, 0x6e, 0x69, 0x73, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x26,
	0x0a, 0x0e, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0x52, 0x0a, 0x0c, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x44,
	0x65, 0x63, 0x6f, 0x64, 0x65, 0x72, 0x12, 0x42, 0x0a, 0x06, 0x44, 0x65, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x1b, 0x2e, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x44, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e,
	0x76, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x63,
	0x6f, 0x64, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x32, 0x60, 0x0a, 0x11, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x67, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x4b, 0x0a, 0x09, 0x52, 0x65, 0x63, 0x6f, 0x67, 0x6e, 0x69, 0x73, 0x65, 0x12, 0x1e, 0x2e, 0x76,
	0x69, 0x64, 0x65, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x63, 0x6f,
	0x67, 0x6e, 0x69, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x76,
	0x69, 0x64, 0x65, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x63, 0x6f,
	0x67, 0x6e, 0x69, 0x73, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x48, 0x0a, 0x19,
	0x63, 0x6f, 0x6d, 0x2e, 0x76, 0x68, 0x69, 0x76, 0x65, 0x2e, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x5f,
	0x61, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63, 0x73, 0x42, 0x0c, 0x76, 0x69, 0x64, 0x65, 0x6f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x01, 0x5a, 0x1b, 0x74, 0x65, 0x73, 0x74, 0x73,
	0x2f, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x5f, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63, 0x73,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_videoservice_proto_rawDescOnce sync.Once
	file_proto_videoservice_proto_rawDescData = file_proto_videoservice_proto_rawDesc
)

func file_proto_videoservice_proto_rawDescGZIP() []byte {
	file_proto_videoservice_proto_rawDescOnce.Do(func() {
		file_proto_videoservice_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_videoservice_proto_rawDescData)
	})
	return file_proto_videoservice_proto_rawDescData
}

var file_proto_videoservice_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_videoservice_proto_goTypes = []interface{}{
	(*DecodeRequest)(nil),    // 0: videoservice.DecodeRequest
	(*DecodeReply)(nil),      // 1: videoservice.DecodeReply
	(*RecogniseRequest)(nil), // 2: videoservice.RecogniseRequest
	(*RecogniseReply)(nil),   // 3: videoservice.RecogniseReply
}
var file_proto_videoservice_proto_depIdxs = []int32{
	0, // 0: videoservice.VideoDecoder.Decode:input_type -> videoservice.DecodeRequest
	2, // 1: videoservice.ObjectRecognition.Recognise:input_type -> videoservice.RecogniseRequest
	1, // 2: videoservice.VideoDecoder.Decode:output_type -> videoservice.DecodeReply
	3, // 3: videoservice.ObjectRecognition.Recognise:output_type -> videoservice.RecogniseReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_videoservice_proto_init() }
func file_proto_videoservice_proto_init() {
	if File_proto_videoservice_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_videoservice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DecodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_videoservice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DecodeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_videoservice_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecogniseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_videoservice_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecogniseReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_videoservice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_videoservice_proto_goTypes,
		DependencyIndexes: file_proto_videoservice_proto_depIdxs,
		MessageInfos:      file_proto_videoservice_proto_msgTypes,
	}.Build()
	File_proto_videoservice_proto = out.File
	file_proto_videoservice_proto_rawDesc = nil
	file_proto_videoservice_proto_goTypes = nil
	file_proto_videoservice_proto_depIdxs = nil
}
