// MIT License
//
// Copyright (c) 2021 Michal Baczun and EASE lab
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProducerConsumerClient is the client API for ProducerConsumer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProducerConsumerClient interface {
	ConsumeString(ctx context.Context, in *ConsumeStringRequest, opts ...grpc.CallOption) (*ConsumeStringReply, error)
	ConsumeStream(ctx context.Context, opts ...grpc.CallOption) (ProducerConsumer_ConsumeStreamClient, error)
}

type producerConsumerClient struct {
	cc grpc.ClientConnInterface
}

func NewProducerConsumerClient(cc grpc.ClientConnInterface) ProducerConsumerClient {
	return &producerConsumerClient{cc}
}

func (c *producerConsumerClient) ConsumeString(ctx context.Context, in *ConsumeStringRequest, opts ...grpc.CallOption) (*ConsumeStringReply, error) {
	out := new(ConsumeStringReply)
	err := c.cc.Invoke(ctx, "/prodcon.ProducerConsumer/ConsumeString", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *producerConsumerClient) ConsumeStream(ctx context.Context, opts ...grpc.CallOption) (ProducerConsumer_ConsumeStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &ProducerConsumer_ServiceDesc.Streams[0], "/prodcon.ProducerConsumer/ConsumeStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &producerConsumerConsumeStreamClient{stream}
	return x, nil
}

type ProducerConsumer_ConsumeStreamClient interface {
	Send(*ConsumeStringRequest) error
	CloseAndRecv() (*ConsumeStringReply, error)
	grpc.ClientStream
}

type producerConsumerConsumeStreamClient struct {
	grpc.ClientStream
}

func (x *producerConsumerConsumeStreamClient) Send(m *ConsumeStringRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *producerConsumerConsumeStreamClient) CloseAndRecv() (*ConsumeStringReply, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ConsumeStringReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ProducerConsumerServer is the server API for ProducerConsumer service.
// All implementations must embed UnimplementedProducerConsumerServer
// for forward compatibility
type ProducerConsumerServer interface {
	ConsumeString(context.Context, *ConsumeStringRequest) (*ConsumeStringReply, error)
	ConsumeStream(ProducerConsumer_ConsumeStreamServer) error
	mustEmbedUnimplementedProducerConsumerServer()
}

// UnimplementedProducerConsumerServer must be embedded to have forward compatible implementations.
type UnimplementedProducerConsumerServer struct {
}

func (UnimplementedProducerConsumerServer) ConsumeString(context.Context, *ConsumeStringRequest) (*ConsumeStringReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConsumeString not implemented")
}
func (UnimplementedProducerConsumerServer) ConsumeStream(ProducerConsumer_ConsumeStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method ConsumeStream not implemented")
}
func (UnimplementedProducerConsumerServer) mustEmbedUnimplementedProducerConsumerServer() {}

// UnsafeProducerConsumerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProducerConsumerServer will
// result in compilation errors.
type UnsafeProducerConsumerServer interface {
	mustEmbedUnimplementedProducerConsumerServer()
}

func RegisterProducerConsumerServer(s grpc.ServiceRegistrar, srv ProducerConsumerServer) {
	s.RegisterService(&ProducerConsumer_ServiceDesc, srv)
}

func _ProducerConsumer_ConsumeString_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsumeStringRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProducerConsumerServer).ConsumeString(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/prodcon.ProducerConsumer/ConsumeString",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProducerConsumerServer).ConsumeString(ctx, req.(*ConsumeStringRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProducerConsumer_ConsumeStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProducerConsumerServer).ConsumeStream(&producerConsumerConsumeStreamServer{stream})
}

type ProducerConsumer_ConsumeStreamServer interface {
	SendAndClose(*ConsumeStringReply) error
	Recv() (*ConsumeStringRequest, error)
	grpc.ServerStream
}

type producerConsumerConsumeStreamServer struct {
	grpc.ServerStream
}

func (x *producerConsumerConsumeStreamServer) SendAndClose(m *ConsumeStringReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *producerConsumerConsumeStreamServer) Recv() (*ConsumeStringRequest, error) {
	m := new(ConsumeStringRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ProducerConsumer_ServiceDesc is the grpc.ServiceDesc for ProducerConsumer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProducerConsumer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "prodcon.ProducerConsumer",
	HandlerType: (*ProducerConsumerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConsumeString",
			Handler:    _ProducerConsumer_ConsumeString_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ConsumeStream",
			Handler:       _ProducerConsumer_ConsumeStream_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/prodcon.proto",
}

// ClientProducerClient is the client API for ClientProducer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClientProducerClient interface {
	ProduceStrings(ctx context.Context, in *ProduceStringsRequest, opts ...grpc.CallOption) (*Empty, error)
}

type clientProducerClient struct {
	cc grpc.ClientConnInterface
}

func NewClientProducerClient(cc grpc.ClientConnInterface) ClientProducerClient {
	return &clientProducerClient{cc}
}

func (c *clientProducerClient) ProduceStrings(ctx context.Context, in *ProduceStringsRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/prodcon.ClientProducer/ProduceStrings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientProducerServer is the server API for ClientProducer service.
// All implementations must embed UnimplementedClientProducerServer
// for forward compatibility
type ClientProducerServer interface {
	ProduceStrings(context.Context, *ProduceStringsRequest) (*Empty, error)
	mustEmbedUnimplementedClientProducerServer()
}

// UnimplementedClientProducerServer must be embedded to have forward compatible implementations.
type UnimplementedClientProducerServer struct {
}

func (UnimplementedClientProducerServer) ProduceStrings(context.Context, *ProduceStringsRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProduceStrings not implemented")
}
func (UnimplementedClientProducerServer) mustEmbedUnimplementedClientProducerServer() {}

// UnsafeClientProducerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientProducerServer will
// result in compilation errors.
type UnsafeClientProducerServer interface {
	mustEmbedUnimplementedClientProducerServer()
}

func RegisterClientProducerServer(s grpc.ServiceRegistrar, srv ClientProducerServer) {
	s.RegisterService(&ClientProducer_ServiceDesc, srv)
}

func _ClientProducer_ProduceStrings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProduceStringsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientProducerServer).ProduceStrings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/prodcon.ClientProducer/ProduceStrings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientProducerServer).ProduceStrings(ctx, req.(*ProduceStringsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClientProducer_ServiceDesc is the grpc.ServiceDesc for ClientProducer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientProducer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "prodcon.ClientProducer",
	HandlerType: (*ClientProducerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProduceStrings",
			Handler:    _ClientProducer_ProduceStrings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/prodcon.proto",
}
