apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/ease-lab/pyaes:var_workload # Stub image. See https://github.com/vhive-serverless/vhive/issues/68
          ports:
            - name: h2c # For GRPC support
              containerPort: 50051

