apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pyaes
  namespace: default
spec:
  template:
    spec:
      runtimeClassName: gvisor
      containers:
        - image: ghcr.io/ease-lab/pyaes:var_workload
          ports:
            - name: h2c # For GRPC support
              containerPort: 50051
