# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mapreduce.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mapreduce.proto',
  package='mapreduce',
  syntax='proto3',
  serialized_options=b'\n\023com.vhive.mapreduceB\tmapreduceP\001Z\025tests/mapreduce/proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fmapreduce.proto\x12\tmapreduce\"\x86\x01\n\nMapRequest\x12\x11\n\tsrcBucket\x18\x01 \x01(\t\x12\x12\n\ndestBucket\x18\x02 \x01(\t\x12\x1d\n\x04keys\x18\x03 \x03(\x0b\x32\x0f.mapreduce.Keys\x12\r\n\x05jobId\x18\x04 \x01(\t\x12\x10\n\x08mapperId\x18\x05 \x01(\x03\x12\x11\n\tnReducers\x18\x06 \x01(\x03\"\x13\n\x04Keys\x12\x0b\n\x03key\x18\x01 \x01(\t\"8\n\x08MapReply\x12\r\n\x05reply\x18\x01 \x01(\t\x12\x1d\n\x04keys\x18\x02 \x03(\x0b\x32\x0f.mapreduce.Keys\"\x8a\x01\n\rReduceRequest\x12\x11\n\tsrcBucket\x18\x01 \x01(\t\x12\x12\n\ndestBucket\x18\x02 \x01(\t\x12\x1d\n\x04keys\x18\x03 \x03(\x0b\x32\x0f.mapreduce.Keys\x12\x11\n\tnReducers\x18\x04 \x01(\x03\x12\r\n\x05jobId\x18\x05 \x01(\t\x12\x11\n\treducerId\x18\x06 \x01(\x03\"\x1c\n\x0bReduceReply\x12\r\n\x05reply\x18\x01 \x01(\t2=\n\x06Mapper\x12\x33\n\x03Map\x12\x15.mapreduce.MapRequest\x1a\x13.mapreduce.MapReply\"\x00\x32G\n\x07Reducer\x12<\n\x06Reduce\x12\x18.mapreduce.ReduceRequest\x1a\x16.mapreduce.ReduceReply\"\x00\x42\x39\n\x13\x63om.vhive.mapreduceB\tmapreduceP\x01Z\x15tests/mapreduce/protob\x06proto3'
)




_MAPREQUEST = _descriptor.Descriptor(
  name='MapRequest',
  full_name='mapreduce.MapRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='srcBucket', full_name='mapreduce.MapRequest.srcBucket', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='destBucket', full_name='mapreduce.MapRequest.destBucket', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='keys', full_name='mapreduce.MapRequest.keys', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='jobId', full_name='mapreduce.MapRequest.jobId', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mapperId', full_name='mapreduce.MapRequest.mapperId', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nReducers', full_name='mapreduce.MapRequest.nReducers', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=165,
)


_KEYS = _descriptor.Descriptor(
  name='Keys',
  full_name='mapreduce.Keys',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='mapreduce.Keys.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=186,
)


_MAPREPLY = _descriptor.Descriptor(
  name='MapReply',
  full_name='mapreduce.MapReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='reply', full_name='mapreduce.MapReply.reply', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='keys', full_name='mapreduce.MapReply.keys', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=244,
)


_REDUCEREQUEST = _descriptor.Descriptor(
  name='ReduceRequest',
  full_name='mapreduce.ReduceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='srcBucket', full_name='mapreduce.ReduceRequest.srcBucket', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='destBucket', full_name='mapreduce.ReduceRequest.destBucket', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='keys', full_name='mapreduce.ReduceRequest.keys', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nReducers', full_name='mapreduce.ReduceRequest.nReducers', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='jobId', full_name='mapreduce.ReduceRequest.jobId', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reducerId', full_name='mapreduce.ReduceRequest.reducerId', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=247,
  serialized_end=385,
)


_REDUCEREPLY = _descriptor.Descriptor(
  name='ReduceReply',
  full_name='mapreduce.ReduceReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='reply', full_name='mapreduce.ReduceReply.reply', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=387,
  serialized_end=415,
)

_MAPREQUEST.fields_by_name['keys'].message_type = _KEYS
_MAPREPLY.fields_by_name['keys'].message_type = _KEYS
_REDUCEREQUEST.fields_by_name['keys'].message_type = _KEYS
DESCRIPTOR.message_types_by_name['MapRequest'] = _MAPREQUEST
DESCRIPTOR.message_types_by_name['Keys'] = _KEYS
DESCRIPTOR.message_types_by_name['MapReply'] = _MAPREPLY
DESCRIPTOR.message_types_by_name['ReduceRequest'] = _REDUCEREQUEST
DESCRIPTOR.message_types_by_name['ReduceReply'] = _REDUCEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MapRequest = _reflection.GeneratedProtocolMessageType('MapRequest', (_message.Message,), {
  'DESCRIPTOR' : _MAPREQUEST,
  '__module__' : 'mapreduce_pb2'
  # @@protoc_insertion_point(class_scope:mapreduce.MapRequest)
  })
_sym_db.RegisterMessage(MapRequest)

Keys = _reflection.GeneratedProtocolMessageType('Keys', (_message.Message,), {
  'DESCRIPTOR' : _KEYS,
  '__module__' : 'mapreduce_pb2'
  # @@protoc_insertion_point(class_scope:mapreduce.Keys)
  })
_sym_db.RegisterMessage(Keys)

MapReply = _reflection.GeneratedProtocolMessageType('MapReply', (_message.Message,), {
  'DESCRIPTOR' : _MAPREPLY,
  '__module__' : 'mapreduce_pb2'
  # @@protoc_insertion_point(class_scope:mapreduce.MapReply)
  })
_sym_db.RegisterMessage(MapReply)

ReduceRequest = _reflection.GeneratedProtocolMessageType('ReduceRequest', (_message.Message,), {
  'DESCRIPTOR' : _REDUCEREQUEST,
  '__module__' : 'mapreduce_pb2'
  # @@protoc_insertion_point(class_scope:mapreduce.ReduceRequest)
  })
_sym_db.RegisterMessage(ReduceRequest)

ReduceReply = _reflection.GeneratedProtocolMessageType('ReduceReply', (_message.Message,), {
  'DESCRIPTOR' : _REDUCEREPLY,
  '__module__' : 'mapreduce_pb2'
  # @@protoc_insertion_point(class_scope:mapreduce.ReduceReply)
  })
_sym_db.RegisterMessage(ReduceReply)


DESCRIPTOR._options = None

_MAPPER = _descriptor.ServiceDescriptor(
  name='Mapper',
  full_name='mapreduce.Mapper',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=417,
  serialized_end=478,
  methods=[
  _descriptor.MethodDescriptor(
    name='Map',
    full_name='mapreduce.Mapper.Map',
    index=0,
    containing_service=None,
    input_type=_MAPREQUEST,
    output_type=_MAPREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MAPPER)

DESCRIPTOR.services_by_name['Mapper'] = _MAPPER


_REDUCER = _descriptor.ServiceDescriptor(
  name='Reducer',
  full_name='mapreduce.Reducer',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=480,
  serialized_end=551,
  methods=[
  _descriptor.MethodDescriptor(
    name='Reduce',
    full_name='mapreduce.Reducer.Reduce',
    index=0,
    containing_service=None,
    input_type=_REDUCEREQUEST,
    output_type=_REDUCEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_REDUCER)

DESCRIPTOR.services_by_name['Reducer'] = _REDUCER

# @@protoc_insertion_point(module_scope)
