apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-0
spec:
  capacity:
    storage: 24Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/ramdisk
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: minio-type
              operator: In
              values:
                - tenant

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-1
spec:
  capacity:
    storage: 24Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/ramdisk
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: minio-type
              operator: In
              values:
                - tenant

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-2
spec:
  capacity:
    storage: 24Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/ramdisk
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: minio-type
              operator: In
              values:
                - tenant

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-3
spec:
  capacity:
    storage: 24Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/ramdisk
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: minio-type
              operator: In
              values:
                - tenant

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-4
spec:
  capacity:
    storage: 24Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/ramdisk
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: minio-type
              operator: In
              values:
                - tenant


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-5
spec:
  capacity:
    storage: 24Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/ramdisk
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: minio-type
              operator: In
              values:
                - tenant


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-6
spec:
  capacity:
    storage: 24Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/ramdisk
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: minio-type
              operator: In
              values:
                - tenant



---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-7
spec:
  capacity:
    storage: 24Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/ramdisk
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: minio-type
              operator: In
              values:
                - tenant
