// MIT License
//
// Copyright (c) 2021 Mert Bora Alper and EASE lab
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: cmd/server/tempReader.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//  "TempReading" is the schema of the incoming requests.
//  Each request shall contain:
//    1. The temperature in celsius.
//    2. The provider of the node (for instance `aws`)
//    3. The zone of the node (for instance `us-east-1`)
//    4. The unique identifier of the node (for example its hostname)
type TempReading struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Celsius  int32  `protobuf:"varint,1,opt,name=celsius,proto3" json:"celsius,omitempty"`
	Provider string `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	Zone     string `protobuf:"bytes,3,opt,name=zone,proto3" json:"zone,omitempty"`
	Machine  string `protobuf:"bytes,4,opt,name=machine,proto3" json:"machine,omitempty"`
}

func (x *TempReading) Reset() {
	*x = TempReading{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_server_tempReader_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TempReading) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TempReading) ProtoMessage() {}

func (x *TempReading) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_server_tempReader_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TempReading.ProtoReflect.Descriptor instead.
func (*TempReading) Descriptor() ([]byte, []int) {
	return file_cmd_server_tempReader_proto_rawDescGZIP(), []int{0}
}

func (x *TempReading) GetCelsius() int32 {
	if x != nil {
		return x.Celsius
	}
	return 0
}

func (x *TempReading) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *TempReading) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *TempReading) GetMachine() string {
	if x != nil {
		return x.Machine
	}
	return ""
}

//  "Response" is the schema of the outgoing responses.
//  Each response shall contain:
//    1. Whether the request was OK or not.
//    2. (Optional) The reason why it was *not* OK, if so.
type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok     bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_server_tempReader_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_server_tempReader_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_cmd_server_tempReader_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Response) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_cmd_server_tempReader_proto protoreflect.FileDescriptor

var file_cmd_server_tempReader_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x63, 0x6d, 0x64, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x74, 0x65, 0x6d,
	0x70, 0x52, 0x65, 0x61, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x71, 0x0a,
	0x0b, 0x54, 0x65, 0x6d, 0x70, 0x52, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x65, 0x6c, 0x73, 0x69, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x63,
	0x65, 0x6c, 0x73, 0x69, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64,
	0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x7a, 0x6f, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x7a, 0x6f, 0x6e, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65,
	0x22, 0x32, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x32, 0x33, 0x0a, 0x0a, 0x54, 0x65, 0x6d, 0x70, 0x52, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x12, 0x25, 0x0a, 0x08, 0x52, 0x65, 0x61, 0x64, 0x54, 0x65, 0x6d, 0x70, 0x12, 0x0c,
	0x2e, 0x54, 0x65, 0x6d, 0x70, 0x52, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x1a, 0x09, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x07, 0x5a, 0x05, 0x2f, 0x6d, 0x61,
	0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cmd_server_tempReader_proto_rawDescOnce sync.Once
	file_cmd_server_tempReader_proto_rawDescData = file_cmd_server_tempReader_proto_rawDesc
)

func file_cmd_server_tempReader_proto_rawDescGZIP() []byte {
	file_cmd_server_tempReader_proto_rawDescOnce.Do(func() {
		file_cmd_server_tempReader_proto_rawDescData = protoimpl.X.CompressGZIP(file_cmd_server_tempReader_proto_rawDescData)
	})
	return file_cmd_server_tempReader_proto_rawDescData
}

var file_cmd_server_tempReader_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cmd_server_tempReader_proto_goTypes = []interface{}{
	(*TempReading)(nil), // 0: TempReading
	(*Response)(nil),    // 1: Response
}
var file_cmd_server_tempReader_proto_depIdxs = []int32{
	0, // 0: TempReader.ReadTemp:input_type -> TempReading
	1, // 1: TempReader.ReadTemp:output_type -> Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cmd_server_tempReader_proto_init() }
func file_cmd_server_tempReader_proto_init() {
	if File_cmd_server_tempReader_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cmd_server_tempReader_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TempReading); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_server_tempReader_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cmd_server_tempReader_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cmd_server_tempReader_proto_goTypes,
		DependencyIndexes: file_cmd_server_tempReader_proto_depIdxs,
		MessageInfos:      file_cmd_server_tempReader_proto_msgTypes,
	}.Build()
	File_cmd_server_tempReader_proto = out.File
	file_cmd_server_tempReader_proto_rawDesc = nil
	file_cmd_server_tempReader_proto_goTypes = nil
	file_cmd_server_tempReader_proto_depIdxs = nil
}
