//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package k8s

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSnapshotCache) DeepCopyInto(out *NodeSnapshotCache) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSnapshotCache.
func (in *NodeSnapshotCache) DeepCopy() *NodeSnapshotCache {
	if in == nil {
		return nil
	}
	out := new(NodeSnapshotCache)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeSnapshotCache) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSnapshotCacheList) DeepCopyInto(out *NodeSnapshotCacheList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeSnapshotCache, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSnapshotCacheList.
func (in *NodeSnapshotCacheList) DeepCopy() *NodeSnapshotCacheList {
	if in == nil {
		return nil
	}
	out := new(NodeSnapshotCacheList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeSnapshotCacheList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSnapshotCacheSpec) DeepCopyInto(out *NodeSnapshotCacheSpec) {
	*out = *in
	if in.Snapshots != nil {
		in, out := &in.Snapshots, &out.Snapshots
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSnapshotCacheSpec.
func (in *NodeSnapshotCacheSpec) DeepCopy() *NodeSnapshotCacheSpec {
	if in == nil {
		return nil
	}
	out := new(NodeSnapshotCacheSpec)
	in.DeepCopyInto(out)
	return out
}
