name: 'LFS Cache Handler'
description: 'Caches and restores LFS objects to reduce bandwidth usage'
inputs:
  lfs_enabled:
    description: 'Whether LFS is used in this repository'
    required: false
    default: 'true'
  ref:  # Add this new input
    description: 'Git ref to checkout'
    required: false
runs:
  using: "composite"
  steps:
    - name: Checkout (LFS disabled)
      if: ${{ inputs.lfs_enabled == 'true' }}
      uses: actions/checkout@v4
      with:
        lfs: false
        ref: ${{ inputs.ref }}

    - name: Generate LFS hash list
      if: ${{ inputs.lfs_enabled == 'true' }}
      shell: bash
      run: git lfs ls-files -l | cut -d' ' -f1 | sort > .git/lfs-hashes.txt

    - name: Restore LFS cache
      if: ${{ inputs.lfs_enabled == 'true' }}
      id: lfs-cache
      uses: actions/cache@v4
      with:
        path: .git/lfs
        key: ${{ runner.os }}-lfs-${{ hashFiles('.git/lfs-hashes.txt') }}
        restore-keys: |
          ${{ runner.os }}-lfs-

    - name: Fetch LFS objects
      if: ${{ inputs.lfs_enabled == 'true' }}
      shell: bash
      run: |
        git lfs fetch --prune
        git lfs checkout
