// Code generated by protoc-gen-go. DO NOT EDIT.
// source: orchestrator.proto

package orchestrator

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the user's name.
type StartVMReq struct {
	Image                string   `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartVMReq) Reset()         { *m = StartVMReq{} }
func (m *StartVMReq) String() string { return proto.CompactTextString(m) }
func (*StartVMReq) ProtoMessage()    {}
func (*StartVMReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_96b6e6782baaa298, []int{0}
}

func (m *StartVMReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartVMReq.Unmarshal(m, b)
}
func (m *StartVMReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartVMReq.Marshal(b, m, deterministic)
}
func (m *StartVMReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartVMReq.Merge(m, src)
}
func (m *StartVMReq) XXX_Size() int {
	return xxx_messageInfo_StartVMReq.Size(m)
}
func (m *StartVMReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StartVMReq.DiscardUnknown(m)
}

var xxx_messageInfo_StartVMReq proto.InternalMessageInfo

func (m *StartVMReq) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *StartVMReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// The request message containing the user's name.
type StopVMsReq struct {
	AllVms               bool     `protobuf:"varint,1,opt,name=all_vms,json=allVms,proto3" json:"all_vms,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopVMsReq) Reset()         { *m = StopVMsReq{} }
func (m *StopVMsReq) String() string { return proto.CompactTextString(m) }
func (*StopVMsReq) ProtoMessage()    {}
func (*StopVMsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_96b6e6782baaa298, []int{1}
}

func (m *StopVMsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopVMsReq.Unmarshal(m, b)
}
func (m *StopVMsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopVMsReq.Marshal(b, m, deterministic)
}
func (m *StopVMsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopVMsReq.Merge(m, src)
}
func (m *StopVMsReq) XXX_Size() int {
	return xxx_messageInfo_StopVMsReq.Size(m)
}
func (m *StopVMsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StopVMsReq.DiscardUnknown(m)
}

var xxx_messageInfo_StopVMsReq proto.InternalMessageInfo

func (m *StopVMsReq) GetAllVms() bool {
	if m != nil {
		return m.AllVms
	}
	return false
}

// The response message containing the greetings
type Status struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_96b6e6782baaa298, []int{2}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*StartVMReq)(nil), "orchestrator.StartVMReq")
	proto.RegisterType((*StopVMsReq)(nil), "orchestrator.StopVMsReq")
	proto.RegisterType((*Status)(nil), "orchestrator.Status")
}

func init() { proto.RegisterFile("orchestrator.proto", fileDescriptor_96b6e6782baaa298) }

var fileDescriptor_96b6e6782baaa298 = []byte{
	// 225 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0x4d, 0xc1, 0x56, 0x1f, 0x43, 0x30, 0x0c, 0x0c, 0x82, 0x20, 0x01, 0xc1, 0x53, 0x0e,
	0xd3, 0x9b, 0xb7, 0xdd, 0x87, 0xa3, 0x83, 0x5e, 0x25, 0x6e, 0x61, 0x06, 0x12, 0x12, 0xf3, 0xde,
	0xc4, 0x3f, 0xc1, 0x3f, 0x5b, 0x9a, 0x5a, 0xda, 0x52, 0x3c, 0x7e, 0x5f, 0xf2, 0x7b, 0xfc, 0xf8,
	0x80, 0x87, 0xb4, 0xff, 0x30, 0x48, 0x49, 0x53, 0x48, 0x2a, 0xa6, 0x40, 0x81, 0x2f, 0xc6, 0x9d,
	0x5c, 0x01, 0xec, 0x48, 0x27, 0x6a, 0x36, 0xb5, 0xf9, 0xe4, 0x4b, 0x38, 0xb7, 0x5e, 0x1f, 0x8d,
	0x60, 0xf7, 0xec, 0xf1, 0xb2, 0xee, 0x02, 0xbf, 0x82, 0xc2, 0x1e, 0x44, 0x91, 0xab, 0xc2, 0x1e,
	0xe4, 0x43, 0xcb, 0x84, 0xd8, 0x6c, 0xb0, 0x65, 0x6e, 0xa0, 0xd2, 0xce, 0xbd, 0x7d, 0x79, 0xcc,
	0xd4, 0x45, 0x5d, 0x6a, 0xe7, 0x1a, 0x8f, 0x52, 0x42, 0xb9, 0x23, 0x4d, 0x27, 0xe4, 0x02, 0x2a,
	0x6f, 0x10, 0x87, 0xc3, 0x7d, 0x5c, 0xfd, 0x30, 0x58, 0xbc, 0x8e, 0x7c, 0xf8, 0x0b, 0x54, 0x7f,
	0x3e, 0x5c, 0xa8, 0x89, 0xfd, 0xa0, 0x79, 0xbb, 0x9c, 0xbd, 0xd0, 0x09, 0xe5, 0x59, 0x07, 0x67,
	0xb1, 0x39, 0xdc, 0xfb, 0xfe, 0x07, 0xaf, 0x9f, 0xe1, 0xce, 0x06, 0x75, 0x4c, 0x71, 0xaf, 0xcc,
	0xb7, 0xf6, 0xd1, 0x19, 0x9c, 0xfc, 0x5c, 0x5f, 0x8f, 0x45, 0xb7, 0xed, 0x96, 0x5b, 0xf6, 0x5e,
	0xe6, 0x51, 0x9f, 0x7e, 0x03, 0x00, 0x00, 0xff, 0xff, 0x56, 0x54, 0xc2, 0x18, 0x6a, 0x01, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// OrchestratorClient is the client API for Orchestrator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrchestratorClient interface {
	StartVM(ctx context.Context, in *StartVMReq, opts ...grpc.CallOption) (*Status, error)
	StopVMs(ctx context.Context, in *StopVMsReq, opts ...grpc.CallOption) (*Status, error)
}

type orchestratorClient struct {
	cc grpc.ClientConnInterface
}

func NewOrchestratorClient(cc grpc.ClientConnInterface) OrchestratorClient {
	return &orchestratorClient{cc}
}

func (c *orchestratorClient) StartVM(ctx context.Context, in *StartVMReq, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/orchestrator.Orchestrator/StartVM", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) StopVMs(ctx context.Context, in *StopVMsReq, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/orchestrator.Orchestrator/StopVMs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrchestratorServer is the server API for Orchestrator service.
type OrchestratorServer interface {
	StartVM(context.Context, *StartVMReq) (*Status, error)
	StopVMs(context.Context, *StopVMsReq) (*Status, error)
}

// UnimplementedOrchestratorServer can be embedded to have forward compatible implementations.
type UnimplementedOrchestratorServer struct {
}

func (*UnimplementedOrchestratorServer) StartVM(ctx context.Context, req *StartVMReq) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartVM not implemented")
}
func (*UnimplementedOrchestratorServer) StopVMs(ctx context.Context, req *StopVMsReq) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopVMs not implemented")
}

func RegisterOrchestratorServer(s *grpc.Server, srv OrchestratorServer) {
	s.RegisterService(&_Orchestrator_serviceDesc, srv)
}

func _Orchestrator_StartVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartVMReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).StartVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/orchestrator.Orchestrator/StartVM",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).StartVM(ctx, req.(*StartVMReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_StopVMs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopVMsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).StopVMs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/orchestrator.Orchestrator/StopVMs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).StopVMs(ctx, req.(*StopVMsReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Orchestrator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "orchestrator.Orchestrator",
	HandlerType: (*OrchestratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartVM",
			Handler:    _Orchestrator_StartVM_Handler,
		},
		{
			MethodName: "StopVMs",
			Handler:    _Orchestrator_StopVMs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "orchestrator.proto",
}
