apiVersion: "power.intel.com/v1"
kind: PowerWorkload
metadata:
  name: performance-node-1.kt-cluster.ntu-cloud-pg0.utah.cloudlab.us-workload
  namespace: intel-power
spec:
  name: "performance-node-1.kt-cluster.ntu-cloud-pg0.utah.cloudlab.us-workload"
  allCores: true
  powerNodeSelector:
    kubernetes.io/hostname: node-1.kt-cluster.ntu-cloud-pg0.utah.cloudlab.us
  powerProfile: "performance"