apiVersion: "power.intel.com/v1"
kind: PowerWorkload
metadata:
  # Replace <NODE_NAME> with the Node you intend this PowerWorkload to be associated with
  name: shared-node-2.power-manager.ntu-cloud-pg0.utah.cloudlab.us-workload
  namespace: intel-power
spec:
  # Replace <NODE_NAME> with the Node you intend this PowerWorkload to be associated with
  name: "shared-node-2.power-manager.ntu-cloud-pg0.utah.cloudlab.us-workload"
  allCores: true
  reservedCPUs:
    # IMPORTANT: The CPUs in reservedCPUs should match the value of the reserved system CPUs in your Kubelet config file
    - 0
    - 1
  powerNodeSelector:
    # The label must be as below, as this workload will be specific to the Node
    kubernetes.io/hostname: node-2.power-manager.ntu-cloud-pg0.utah.cloudlab.us
  # Replace this value with the intended shared PowerProfile
  powerProfile: "shared"