FROM vhiveease/cri_dev_env

RUN sudo apt remove -y vim tmux
COPY scripts/github_runner/setup_runner_cri.sh /scripts/
RUN chmod +x /scripts/setup_runner_cri.sh 

ENTRYPOINT ["/usr/local/bin/entrypoint","/scripts/setup_runner_cri.sh","/sbin/init"]