FROM kindest/node:v1.20.2

RUN apt-get update && \
    apt-get install --yes \
    apt-utils && \
    apt-get install --yes \
    sudo \
    wget curl\
    gcc g++\
    iproute2 iptables net-tools \
    apt-transport-https \
    ca-certificates \
    make jq \
    acl \
    git git-lfs \
    bc \
    dmsetup \
    gnupg-agent \
    apt-transport-https software-properties-common pkg-config \
    libseccomp-dev libseccomp2 \
    unzip tar \
    socat \
    util-linux \
    ipvsadm \
    tmux vim && \
    sudo wget -O /usr/local/bin/kn -c "https://github.com/knative/client/releases/download/v0.20.0/kn-linux-amd64" && \
    sudo chmod +x /usr/local/bin/kn && \
    mkdir /scripts
COPY scripts/github_runner/setup_cri_dev_env.sh /scripts/
COPY scripts/setup_system.sh /scripts/
COPY scripts/create_devmapper.sh /scripts/
RUN chmod +x /scripts/setup_system.sh && \
    chmod +x /scripts/create_devmapper.sh && \
    chmod +x /scripts/setup_cri_dev_env.sh

ENTRYPOINT ["/usr/local/bin/entrypoint","/scripts/setup_cri_dev_env.sh","/sbin/init"]