FROM kindest/node:v1.20.2

RUN mkdir /scripts
COPY scripts/github_runner/setup_runner_cri.sh /scripts/
COPY scripts/setup_system.sh /scripts/
COPY scripts/create_devmapper.sh /scripts/
RUN chmod +x /scripts/setup_runner_cri.sh && \
    chmod +x /scripts/setup_system.sh && \
    chmod +x /scripts/create_devmapper.sh

ENTRYPOINT ["/usr/local/bin/entrypoint","/scripts/setup_runner_cri.sh","/sbin/init"]