name: vHive CRI tests

on:
  workflow_call:
    inputs:
      sandbox:
        required: true
        type: string

env:
  GO111MODULE: on

jobs:
  cri-tests:
    name: CRI tests
    env:
      GITHUB_RUN_ID: ${{ github.run_id }}
      GITHUB_VHIVE_ARGS: "-dbg"
    runs-on: ubuntu-24.04

    steps:
      - name: Host Info
        run: |
          echo $HOSTNAME
          echo $GITHUB_RUN_ID
      
      # added to enable KVM access as default not enabled on github runners
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
          # sudo chmod 666 /dev/kvm
          # Verify KVM is accessible (Debugging purpose)
          ls -la /dev/kvm
          [ -r /dev/kvm ] && [ -w /dev/kvm ] || exit 1

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go version in go.mod file
        uses: actions/setup-go@v6
        with:
          go-version-file: ${{ github.workspace }}/go.mod
          cache-dependency-path: |
            **/go.sum
            **/go.mod

      - name: Add rsync
        run: |
          sudo apt update
          sudo apt install rsync -y

      - name: Build setup scripts
        run: pushd scripts && go build -o setup_tool && popd
           
      - name: Setup System
        run: ./scripts/setup_tool setup_system

      - name: Setup Node
        run: ./scripts/setup_tool setup_node ${{ inputs.sandbox }}

      - name: Setup vHive CRI test environment
        run: ./scripts/github_runner/setup_cri_test_env.sh ${{ inputs.sandbox }}

      - name: Run vHive CRI tests
        run: source /etc/profile && go clean -testcache && go test ./cri -v -race -cover

      - name: Run sandbox specific tests
        if: ${{ inputs.sandbox == 'firecracker' }}
        run: source /etc/profile && go clean -testcache && go test ./cri/${{ inputs.sandbox }} -v -race -cover

      - name: Archive log artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v5
        with:
          name: ctrd-logs
          path: |
            /tmp/ctrd-logs/${{ github.run_id }}
            ${{ github.workspace }}/*.log
            ${{ github.workspace }}/scripts/github_runner/*.log