name: Build and Test OpenYurt Deployer

on:
    push:
      branches: [ main, legacy-firecracker-v0.24.0-with-upf-support ]
      paths-ignore:
      - 'docs/**'
      - '**.md'
    pull_request:
      branches: [ main, legacy-firecracker-v0.24.0-with-upf-support ]
      paths-ignore:
      - 'docs/**'
      - '**.md'
    workflow_dispatch:

env:
    GOOS: linux
    GO111MODULE: on

jobs:
  openyurt-unit-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v5

    - name: Set up Go version in go.mod file
      uses: actions/setup-go@v6
      with:
        go-version-file: ${{ github.workspace }}/go.mod
        cache-dependency-path: |
          **/go.sum
          **/go.mod

    - name: Build scripts
      run: 
        pushd scripts/openyurt-deployer && go build -o oy_deploy && popd

    - name: Run Unit Test on OpenYurt helper function 
      run: | 
        cd scripts/openyurt-deployer
        chmod +x unit_test_workflow.sh
        ./unit_test_workflow.sh