name: vHive stock-only stargz tests

on:
  push:
    branches: [ main, legacy-firecracker-v0.24.0-with-upf-support ]
    paths:
    - 'docs/**'
    - '**.md'
    - 'function-images/**'
  pull_request:
    branches: [ main, legacy-firecracker-v0.24.0-with-upf-support ]
    paths:
    - 'docs/**'
    - '**.md'
    - 'function-images/**'
  workflow_dispatch:

env:
  GOOS: linux
  GO111MODULE: on

jobs:
  stargz-container-test:
    name: Test running stargz-based image using kn
    runs-on: ubuntu-24.04
    steps:
      - run: 'echo "This check not required"'